[project]
name = "leetcode-all"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.17.1",
    "ruff>=0.12.9",
]

[dependency-groups]
dev = [
    "icecream>=2.1.7",
    "memory-profiler>=0.61.0",
]
